# Project properties
sonar.projectKey=esqa_mvp_sonar
sonar.projectVersion=1
sonar.host.url=https://devstack.vwgroup.com/sonar
sonar.language=py
sonar.coverage.exclusions=**tests**,**connections/s3**,**common/sparkdelta**,src/common/util/core_utils.py,src/common/spark_application.py,src/common/sparkdelta/delta_operations.py,src/inbox_to_landing/main.py,src/landing_to_storage/main.py,src/connections/s3/s3.py,src/connections/s3/s3_operations.py,src/inbox_to_landing/inbox_mover.py,src/common/log/log.py
sonar.dynamicAnalysis=reuseReports
sonar.core.codeCoveragePlugin=cobertura
sonar.python.coveragePlugin=cobertura
sonar.sources=src

# Test Results
sonar.python.xunit.reportPath=test_results.xml
# Coverage
sonar.python.coverage.reportPaths=coverage.xml