# Project properties
sonar.projectKey=sqa:fvr_conbase_sonar
sonar.projectName=fvr_conbase_sonar
sonar.projectVersion=1
sonar.host.url=https://devstack.vwgroup.com/sonar
sonar.language=py
sonar.coverage.exclusions=venv/**,tests/**,src/common/**,src/connections/**,src/conbase_interface/main.py,src/ingestion/main.py
sonar.dynamicAnalysis=reuseReports
sonar.core.codeCoveragePlugin=cobertura
sonar.python.coveragePlugin=cobertura
sonar.sources=src
sonar.python.xunit.skipDetails=true

# Test Results
sonar.python.xunit.reportPath=test_results.xml
# Coverage
sonar.python.coverage.reportPaths=coverage.xml
